// <auto-generated />
using System;
using JAP_Task_1_MoviesApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JAP_Task_1_MoviesApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210915194018_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.Property<int>("ActorsId")
                        .HasColumnType("int");

                    b.Property<int>("MoviesId")
                        .HasColumnType("int");

                    b.HasKey("ActorsId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("ActorMovie");
                });

            modelBuilder.Entity("JAP_Task_1_MoviesApi.Models.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Morgan",
                            Surname = "Freeman"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bob",
                            Surname = "Gunton"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tim",
                            Surname = "Robbins"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Marlon",
                            Surname = "Brando"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Al",
                            Surname = "Pacino"
                        },
                        new
                        {
                            Id = 6,
                            Name = "James",
                            Surname = "Caan"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Robert",
                            Surname = "De Niro"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Robert",
                            Surname = "Duvall"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Christian",
                            Surname = "Bale"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Heath",
                            Surname = "Ledger"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Aaron",
                            Surname = "Eckhart"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Henry",
                            Surname = "Fonda"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Lee",
                            Surname = "J. Cobb"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Martin",
                            Surname = "Balsam"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Liam",
                            Surname = "Neeson"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Ralph",
                            Surname = "Fiennes"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Ben",
                            Surname = "Kingsley"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Elijah",
                            Surname = "Wood"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Viggo",
                            Surname = "Mortensen"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Ian",
                            Surname = "McKellen"
                        },
                        new
                        {
                            Id = 21,
                            Name = "John",
                            Surname = "Travolta"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Uma",
                            Surname = "Thurman"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Samuel",
                            Surname = "L. Jackson"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Clint",
                            Surname = "Eastwood"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Eli",
                            Surname = "Wallach"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Lee",
                            Surname = "Van Cleef"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Orlando",
                            Surname = "Bloom"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Brad",
                            Surname = "Pitt"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Edward",
                            Surname = "Norton"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Meat",
                            Surname = "Loaf"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Tom",
                            Surname = "Hanks"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Robin",
                            Surname = "Wright"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Gary",
                            Surname = "Sinise"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Leonardo",
                            Surname = "DiCaprio"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Joseph",
                            Surname = "Gordon-Levitt"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Elliot",
                            Surname = "Page"
                        },
                        new
                        {
                            Id = 37,
                            Name = "David",
                            Surname = "Attenborough"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Sigourney",
                            Surname = "Weaver"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Nikolay",
                            Surname = "Drozdov"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Bryan",
                            Surname = "Cranston"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Aaron",
                            Surname = "Paul"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Anna",
                            Surname = "Gunn"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Scott",
                            Surname = "Grimes"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Damian",
                            Surname = "Lewis"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Ron",
                            Surname = "Livingston"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Jessie",
                            Surname = "Buckley"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Jared",
                            Surname = "Harris"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Stellan",
                            Surname = "Skarsgard"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Jessie",
                            Surname = "Buckley"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Dominic",
                            Surname = "West"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Lance",
                            Surname = "Reddick"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Sonja",
                            Surname = "Sohn"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Peter",
                            Surname = "Drost"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Roger",
                            Surname = "Horrocks"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Neil",
                            Surname = "deGrasse Tyson"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Stoney",
                            Surname = "Emshwiller"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Piotr",
                            Surname = "Michael"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Neil",
                            Surname = "deGrasse Tyson"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Dee",
                            Surname = "Bradley Baker"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Zach",
                            Surname = "Tyler"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Mae",
                            Surname = "Whitman"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Carl",
                            Surname = "Sagan"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Jaromir",
                            Surname = "Hanzlik"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Jonathan",
                            Surname = "Fahn"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Emilia",
                            Surname = "Clarke"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Peter",
                            Surname = "Dinklage"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Kit",
                            Surname = "Harington"
                        },
                        new
                        {
                            Id = 68,
                            Name = "James",
                            Surname = "Gandolfini"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Lorraine",
                            Surname = "Bracco"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Eddie",
                            Surname = "Falco"
                        });
                });

            modelBuilder.Entity("JAP_Task_1_MoviesApi.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Overview")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PosterPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Overview = "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/iXbWpCkIauBMStSTUT9v4GXvdgH.jpg",
                            ReleaseDate = new DateTime(2021, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Suicide Squad",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 2,
                            Overview = "A devastated husband vows to bring justice to the people responsible for his wife's death while protecting the only family he has left, his daughter.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/cP7odDzzFBD9ycxj2laTeFWGLjD.jpg",
                            ReleaseDate = new DateTime(2021, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sweet Girl",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 3,
                            Overview = "Dr. Lily Houghton enlists the aid of wisecracking skipper Frank Wolff to take her down the Amazon in his dilapidated boat. Together, they search for an ancient tree that holds the power to heal – a discovery that will change the future of medicine.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/9dKCd55IuTT5QRs989m9Qlb7d2B.jpg",
                            ReleaseDate = new DateTime(2021, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jungle Cruise",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 4,
                            Overview = "Ryder and the pups are called to Adventure City to stop Mayor Humdinger from turning the bustling metropolis into a state of chaos...",
                            PosterPath = "https://image.tmdb.org/t/p/w500/ic0intvXZSfBlYPIvWXpU1ivUCO.jpg",
                            ReleaseDate = new DateTime(2021, 8, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "PAW Patrol: The Movie",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 5,
                            Overview = "A rooster and his fowl partner embark on a dangerous trip to the Congo to recover their stolen eggs from a group of Russian goons.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/wrlQnKHLCBheXMNWotyr5cVDqNM.jpg",
                            ReleaseDate = new DateTime(2021, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Eggs Run",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 6,
                            Overview = "Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/qAZ0pzat24kLdO3o8ejmbLxyOac.jpg",
                            ReleaseDate = new DateTime(2021, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Black Widow",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 7,
                            Overview = "When LeBron and his young son Dom are trapped in a digital space by a rogue A.I., LeBron must get them home safe by leading Bugs, Lola Bunny and the whole gang of notoriously undisciplined Looney Tunes to victory over the A.I.'s digitized champions on the court. It's Tunes versus Goons in the highest-stakes challenge of his life.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/5bFK5d3mVTAvBCXi5NPWH0tYjKl.jpg",
                            ReleaseDate = new DateTime(2021, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Space Jam: A New Legacy",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 8,
                            Overview = "A man will become a criminal to save his family.  Director: Shawn Welling  Writer: Derek H. Potts  Stars: Tom Vera, Tom Sizemore, Lee Majors",
                            PosterPath = "https://image.tmdb.org/t/p/w500/7p0O4mKYLIhU2E5Zcq9Z3vOZ4e9.jpg",
                            ReleaseDate = new DateTime(2021, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Narco Sub",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 9,
                            Overview = "A bank teller called Guy realizes he is a background character in an open world video game called Free City that will soon go offline.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/hEqw9swA8gFJuNjgWYEypwZfkZg.jpg",
                            ReleaseDate = new DateTime(2021, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Free Guy",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 10,
                            Overview = "Evan McCauley has skills he never learned and memories of places he has never visited. Self-medicated and on the brink of a mental breakdown, a secret group that call themselves “Infinites” come to his rescue, revealing that his memories are real.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/niw2AKHz6XmwiRMLWaoyAOAti0G.jpg",
                            ReleaseDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Infinite",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 11,
                            Overview = "Whilst vacationing in Greece, Beckett, becomes the target of a manhunt after a devastating car accident forces him to run for his life across the country to clear his name but tensions escalate as the authorities close in and political unrest mounts which makes Beckett fall even deeper into a dangerous web of conspiracy.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/fBJducGBcmrcIOQdhm4BUBNDiMu.jpg",
                            ReleaseDate = new DateTime(2021, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Beckett",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 12,
                            Overview = "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg",
                            ReleaseDate = new DateTime(2021, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "F9",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 13,
                            Overview = "The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/kv2Qk9MKFFQo4WQPaYta599HkJP.jpg",
                            ReleaseDate = new DateTime(2021, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Boss Baby",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 14,
                            Overview = "A waiter pretends to be an important businessman in order to reach the upper class through his entrepreneurial dreams.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/zvGC5jX5wQmU1GgPc0VGZz7Mtcs.jpg",
                            ReleaseDate = new DateTime(2021, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "El mesero",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 15,
                            Overview = "Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/jTswp6KyDYKtvC52GbHagrZbGvD.jpg",
                            ReleaseDate = new DateTime(2021, 6, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Luca",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 16,
                            Overview = "The world is stunned when a group of time travelers arrive from the year 2051 to deliver an urgent message: Thirty years in the future, mankind is losing a global war against a deadly alien species. The only hope for survival is for soldiers and civilians from the present to be transported to the future and join the fight. Among those recruited is high school teacher and family man Dan Forester. Determined to save the world for his young daughter, Dan teams up with a brilliant scientist and his estranged father in a desperate quest to rewrite the fate of the planet.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/34nDCQZwaEvsy4CFO5hkGRFDCVU.jpg",
                            ReleaseDate = new DateTime(2021, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Tomorrow War",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 17,
                            Overview = "",
                            PosterPath = "https://image.tmdb.org/t/p/w500/oxNoVgbu2v9ETL93Kri1pw8osYf.jpg",
                            ReleaseDate = new DateTime(2021, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Breathless",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 18,
                            Overview = "A mysterious former secret service agent must urgently return to France when his estranged son  is falsely accused of arms and drug trafficking by the government, following a blunder by an overzealous bureaucrat and a mafia operation.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/ttpKJ7XQxDZV252KNEHXtykYT41.jpg",
                            ReleaseDate = new DateTime(2021, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Last Mercenary",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 19,
                            Overview = "The Loud family travel to Scotland and discover they are descendants of Scottish royalty as they move into their giant ancestral castle.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/mab5wPeGVjbMyYMzyzfdKKnG9cl.jpg",
                            ReleaseDate = new DateTime(2021, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Loud House Movie",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 20,
                            Overview = "Lindy is an acid-tongued woman with rage issues who controls her temper by shocking herself with an electrode vest. One day she makes a connection with Justin, who gives her a glimmer of hope for a shock-free future, but when he’s murdered she launches herself on a revenge-fueled rampage in pursuit of his killer.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/gYZAHan5CHPFXORpQMvOjCTug4E.jpg",
                            ReleaseDate = new DateTime(2021, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jolt",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 21,
                            Overview = "The film centers on the love relationship among the band's bassist Haruki Nakayama, drummer Akihiko Kaji, and Akihiko's roommate and ex-boyfriend Ugetsu Murata.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/xKCtoYHUyX8zAg68eemnYa2orep.jpg",
                            ReleaseDate = new DateTime(2021, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Given",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 22,
                            Overview = "Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/2CAL2433ZeIihfX1Hb2139CX0pW.jpg",
                            ReleaseDate = new DateTime(1995, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dilwale Dulhania Le Jayenge",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 23,
                            Overview = "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
                            ReleaseDate = new DateTime(1994, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Shawshank Redemption",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 24,
                            Overview = "Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
                            ReleaseDate = new DateTime(1972, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 25,
                            Overview = "Professor Gabriel Emerson finally learns the truth about Julia Mitchell's identity, but his realization comes a moment too late. Julia is done waiting for the well-respected Dante specialist to remember her and wants nothing more to do with him. Can Gabriel win back her heart before she finds love in another's arms?",
                            PosterPath = "https://image.tmdb.org/t/p/w500/x5o8cLZfEXMoZczTYWLrUo1P7UJ.jpg",
                            ReleaseDate = new DateTime(2020, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gabriel's Inferno Part II",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 26,
                            Overview = "The final part of the film adaption of the erotic romance novel Gabriel's Inferno written by an anonymous Canadian author under the pen name Sylvain Reynard.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/fYtHxTxlhzD4QWfEbrC1rypysSD.jpg",
                            ReleaseDate = new DateTime(2020, 11, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gabriel's Inferno Part III",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 27,
                            Overview = "An intriguing and sinful exploration of seduction, forbidden love, and redemption, Gabriel's Inferno is a captivating and wildly passionate tale of one man's escape from his own personal hell as he tries to earn the impossible--forgiveness and love.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/oyG9TL7FcRP4EZ9Vid6uKzwdndz.jpg",
                            ReleaseDate = new DateTime(2020, 5, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gabriel's Inferno",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 28,
                            Overview = "The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg",
                            ReleaseDate = new DateTime(1993, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Schindler's List",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 29,
                            Overview = "In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
                            ReleaseDate = new DateTime(1974, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather: Part II",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 30,
                            Overview = "High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/q719jXXEzOoYaps6babgKnONONX.jpg",
                            ReleaseDate = new DateTime(2016, 8, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Your Name.",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 31,
                            Overview = "Just as Tessa's life begins to become unglued, nothing is what she thought it would be. Not her friends nor her family. The only person that she should be able to rely on is Hardin, who is furious when he discovers the massive secret that she's been keeping. Before Tessa makes the biggest decision of her life, everything changes because of revelations about her family.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/oOZITZodAja6optBgLh8ZZrgzbb.jpg",
                            ReleaseDate = new DateTime(2021, 9, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "After We Fell",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 32,
                            Overview = "A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
                            ReleaseDate = new DateTime(2001, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spirited Away",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 33,
                            Overview = "Born free in the American West, Black Beauty is a horse rounded up and brought to Birtwick Stables, where she meets spirited teenager Jo Green. The two forge a bond that carries Beauty through the different chapters, challenges and adventures.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/5ZjMNJJabwBEnGVQoR2yoMEL9um.jpg",
                            ReleaseDate = new DateTime(2020, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Black Beauty",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 34,
                            Overview = "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
                            ReleaseDate = new DateTime(2019, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Parasite",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 35,
                            Overview = "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/velWPhVMQeQKcxggNEU8YmIo52R.jpg",
                            ReleaseDate = new DateTime(1999, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Green Mile",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 36,
                            Overview = "After 8-year-old So-won narrowly survives a brutal sexual assault, her family labors to help her heal while coping with their own rage and grief.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/x9yjkm9gIz5qI5fJMUTfBnWiB2o.jpg",
                            ReleaseDate = new DateTime(2013, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Hope",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 37,
                            Overview = "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/e02s4wmTAExkKg0yF4dEG98ZRpK.jpg",
                            ReleaseDate = new DateTime(1957, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "12 Angry Men",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 38,
                            Overview = "Darth Vader is adamant about turning Luke Skywalker to the dark side. Master Yoda trains Luke to become a Jedi Knight while his friends try to fend off the Imperial fleet.",
                            PosterPath = "https://images.penguinrandomhouse.com/cover/9780345320223",
                            ReleaseDate = new DateTime(1980, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: The Empire Strikes Back (Episode V)",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 39,
                            Overview = "Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades. After their guide is killed by raptors, the team tries to escape the park – but the hunters quickly become the hunted. Even worse, the park’s manager suspects Parker of being a spy and sends a hit squad after her. This battle’s about to become primitive!",
                            PosterPath = "https://image.tmdb.org/t/p/w500/CGJAj5kNWQZypNgUSTTQrFlnG.jpg",
                            ReleaseDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jurassic Hunt",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 40,
                            Overview = "The Blind Man has been hiding out for several years in an isolated cabin and has taken in and raised a young girl orphaned from a devastating house fire. Their quiet life together is shattered when a group of criminals kidnap the girl, forcing the Blind Man to leave his safe haven to save her.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/hRMfgGFRAZIlvwVWy8DYJdLTpvN.jpg",
                            ReleaseDate = new DateTime(2021, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Don't Breathe 2",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 41,
                            Overview = "An off-duty SAS soldier, Tom Buckingham, must thwart a terror attack on a train running through the Channel Tunnel. As the action escalates on the train, events transpire in the corridors of power that may make the difference as to whether Buckingham and the civilian passengers make it out of the tunnel alive.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/6Y9fl8tD1xtyUrOHV2MkCYTpzgi.jpg",
                            ReleaseDate = new DateTime(2021, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "SAS: Red Notice",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 42,
                            Overview = "Cinderella, an orphaned girl with an evil stepmother, has big dreams and with the help of her Fabulous Godmother, she perseveres to make them come true.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/clDFqATL4zcE7LzUwkrVj3zHvk7.jpg",
                            ReleaseDate = new DateTime(2021, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cinderella",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 43,
                            Overview = "Madison is paralyzed by shocking visions of grisly murders, and her torment worsens as she discovers that these waking dreams are in fact terrifying realities.",
                            PosterPath = "https://image.tmdb.org/t/p/w500/dGv2BWjzwAz6LB8a8JeRIZL8hSz.jpg",
                            ReleaseDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Malignant",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 44,
                            Overview = "A wanted fugitive mysteriously surrenders himself to the FBI and offers to help them capture deadly criminals. His sole condition is that he will work only with the new profiler, Elizabeth Keen.",
                            PosterPath = "https://static.wikia.nocookie.net/blacklist/images/5/57/Season_7_Poster.jpg",
                            ReleaseDate = new DateTime(2013, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Blacklist",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 45,
                            Overview = "After Princess Leia, the leader of the Rebel Alliance, is held hostage by Darth Vader, Luke and Han Solo must free her and destroy the powerful weapon created by the Galactic Empire.",
                            PosterPath = "https://kbimages1-a.akamaihd.net/538b1473-6d45-47f4-b16e-32a0a6ba7f9a/1200/1200/False/star-wars-episode-iv-a-new-hope-3.jpg",
                            ReleaseDate = new DateTime(1997, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: A New Hope (Episode IV)",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 46,
                            Overview = "Luke Skywalker attempts to bring his father back to the light side of the Force. At the same time, the rebels hatch a plan to destroy the second Death Star.",
                            PosterPath = "https://m.media-amazon.com/images/I/91LlN7J+Z9L._SL1500_.jpg",
                            ReleaseDate = new DateTime(1983, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: Return of the Jedi (Episode VI)",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 47,
                            Overview = "A new order threatens to destroy the New Republic. Finn, Rey and Poe, backed by the Resistance and the Republic, must find a way to stop them and find Luke, the last surviving Jedi.",
                            PosterPath = "https://m.media-amazon.com/images/M/MV5BOTAzODEzNDAzMl5BMl5BanBnXkFtZTgwMDU1MTgzNzE@._V1_.jpg",
                            ReleaseDate = new DateTime(2015, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: The Force Awakens (Episode VII)",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 48,
                            Overview = "Rey seeks to learn the ways of the Jedi under Luke Skywalker, its remaining member, to reinvigorate the Resistance's war against the First Order.",
                            PosterPath = "https://i.pinimg.com/originals/f4/5a/ea/f45aea75f65c0feb5cbe168f17a9a087.jpg",
                            ReleaseDate = new DateTime(2017, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: The Last Jedi (Episode VIII)",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 49,
                            Overview = "The revival of Emperor Palpatine resurrects the battle between the Resistance and the First Order while the Jedi's legendary conflict with the Sith Lord comes to a head.",
                            PosterPath = "https://lumiere-a.akamaihd.net/v1/images/star-wars-the-rise-of-skywalker-theatrical-poster-1000_ebc74357.jpeg?region=0%2C0%2C891%2C1372",
                            ReleaseDate = new DateTime(2019, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: The Rise of Skywalker (Episode IX)",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 50,
                            Overview = "Jedi Knights Qui-Gon Jinn and Obi-Wan Kenobi set out to stop the Trade Federation from invading Naboo. While travelling, they come across a gifted boy, Anakin, and learn that the Sith have returned.",
                            PosterPath = "https://play-lh.googleusercontent.com/sR1pzOxnF50WLR3vUqXYFvY01_tLD4XPn1RDHf0Xh-W04Vek_3iiZ98U7Db2JcmrqS8",
                            ReleaseDate = new DateTime(1999, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: The Phantom Menace (Episode I)",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 51,
                            Overview = "While pursuing an assassin, Obi Wan uncovers a sinister plot to destroy the Republic. With the fate of the galaxy hanging in the balance, the Jedi must defend the galaxy against the evil Sith.",
                            PosterPath = "https://m.media-amazon.com/images/M/MV5BMDAzM2M0Y2UtZjRmZi00MzVlLTg4MjEtOTE3NzU5ZDVlMTU5XkEyXkFqcGdeQXVyNDUyOTg3Njg@._V1_.jpg",
                            ReleaseDate = new DateTime(2002, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: Attack of the Clones (Episode II)",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 52,
                            Overview = "Anakin joins forces with Obi-Wan and sets Palpatine free from th evil clutches of Count Doku. However, he falls prey to Palpatine and the Jedis' mind games and gives into temptation.",
                            PosterPath = "https://play-lh.googleusercontent.com/mMyoXM8bf72KK-Udap4-hAvqqdXgn0AIBXkS8zejT0RXITIh8oK9a-SYIVk89CA0rHJi",
                            ReleaseDate = new DateTime(2005, 4, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Star Wars: Revenge of the Sith (Episode III)",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 53,
                            Overview = "Jake, who is paraplegic, replaces his twin on the Na'vi inhabited Pandora for a corporate mission. After the natives accept him as one of their own, he must decide where his loyalties lie.",
                            PosterPath = "https://i.pinimg.com/originals/17/aa/71/17aa718c1ab15b482505b8431cf596fc.jpg",
                            ReleaseDate = new DateTime(2009, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avatar",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 54,
                            Overview = "A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.",
                            PosterPath = "https://upload.wikimedia.org/wikipedia/en/4/45/Good_the_bad_and_the_ugly_poster.jpg",
                            ReleaseDate = new DateTime(1996, 12, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Good, the Bad and the Ugly",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 55,
                            Overview = "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                            PosterPath = "https://prod.miramax.digital/media/assets/Pulp-Fiction1.png",
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 56,
                            Overview = "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
                            PosterPath = "https://images.moviesanywhere.com/198e228b071c60f5ad57e5f62fe60029/ff22cad6-2218-414d-b853-3f95d76905c7.jpg?h=375&resize=fit&w=250",
                            ReleaseDate = new DateTime(2001, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lord of the Rings: The Fellowship of the Ring",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 57,
                            Overview = "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
                            PosterPath = "https://m.media-amazon.com/images/I/51v5ZpFyaFL._AC_.jpg",
                            ReleaseDate = new DateTime(1999, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fight Club",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 58,
                            Overview = "The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
                            PosterPath = "https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/37a5b434647543.56d846b10ca45.jpg",
                            ReleaseDate = new DateTime(1994, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Forrest Gump",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 59,
                            Overview = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
                            PosterPath = "https://m.media-amazon.com/images/I/81p+xe8cbnL._SY445_.jpg",
                            ReleaseDate = new DateTime(2010, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception",
                            Type = (short)0
                        },
                        new
                        {
                            Id = 60,
                            Overview = "Wildlife documentary series with David Attenborough, beginning with a look at the remote islands which offer sanctuary to some of the planet's rarest creatures, to the beauty of cities, which are home to humans, and animals..",
                            PosterPath = "https://blackwells.co.uk/jacket/l/9781785943041.jpg",
                            ReleaseDate = new DateTime(2016, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Planet Earth II",
                            Type = (short)1
                        },
                        new
                        {
                            Id = 61,
                            Overview = "Emmy Award-winning, 11 episodes, five years in the making, the most expensive nature documentary series ever commissioned by the BBC, and the first to be filmed in high definition.",
                            PosterPath = "https://m.media-amazon.com/images/I/91X9p6+58KL._SY445_.jpg",
                            ReleaseDate = new DateTime(2010, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Planet Earth",
                            Type = (short)1
                        },
                        new
                        {
                            Id = 62,
                            Overview = "A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family's future.",
                            PosterPath = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
                            ReleaseDate = new DateTime(2008, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Breaking Bad",
                            Type = (short)1
                        },
                        new
                        {
                            Id = 63,
                            Overview = "The story of Easy Company of the U.S. Army 101st Airborne Division and their mission in World War II Europe, from Operation Overlord to V-J Day.",
                            PosterPath = "https://i.dailymail.co.uk/i/pix/2017/02/13/01/3D24EF6B00000578-4215748-image-a-63_1486948627611.jpg",
                            ReleaseDate = new DateTime(2001, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Band of Brothers",
                            Type = (short)1
                        },
                        new
                        {
                            Id = 64,
                            Overview = "In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world's worst man-made catastrophes.",
                            PosterPath = "https://i.redd.it/bv5isr69yr531.png",
                            ReleaseDate = new DateTime(1986, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chernobyl",
                            Type = (short)1
                        },
                        new
                        {
                            Id = 65,
                            Overview = "The Baltimore drug scene, as seen through the eyes of drug dealers and law enforcement.",
                            PosterPath = "https://tvshows.today/wp-content/uploads/the-wire-season-1-poster.jpg",
                            ReleaseDate = new DateTime(2008, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Wire",
                            Type = (short)1
                        },
                        new
                        {
                            Id = 66,
                            Overview = "David Attenborough returns to the world's oceans in this sequel to the acclaimed documentary filming rare and unusual creatures of the deep, as well as documenting the problems our oceans face.",
                            PosterPath = "https://cdn.shopify.com/s/files/1/0747/3829/products/mL1006_1024x1024.jpg?v=1571445246",
                            ReleaseDate = new DateTime(2017, 10, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Blue Planet II",
                            Type = (short)1
                        },
                        new
                        {
                            Id = 67,
                            Overview = "Documentary series focusing on the breadth of the diversity of habitats around the world, from the remote Arctic wilderness and mysterious deep oceans to the vast landscapes of Africa and diverse jungles of South America.",
                            PosterPath = "https://www.penguin.co.uk/content/dam/prh/books/111/1115210/9780593079768.jpg.transform/PRHDesktopWide_small/image.jpg",
                            ReleaseDate = new DateTime(2019, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Our Planet",
                            Type = (short)1
                        },
                        new
                        {
                            Id = 68,
                            Overview = "An exploration of our discovery of the laws of nature and coordinates in space and time.",
                            PosterPath = "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5945/5945188_sa.jpg;maxHeight=640;maxWidth=550",
                            ReleaseDate = new DateTime(2014, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cosmos: A Spacetime Odyssey",
                            Type = (short)1
                        },
                        new
                        {
                            Id = 69,
                            Overview = "In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.",
                            PosterPath = "https://images-na.ssl-images-amazon.com/images/I/914eUC4XPML.jpg",
                            ReleaseDate = new DateTime(2005, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avatar: The Last Airbender",
                            Type = (short)1
                        },
                        new
                        {
                            Id = 70,
                            Overview = "Astronomer Carl Sagan leads us on an engaging guided tour of the various elements and cosmological theories of the universe.",
                            PosterPath = "https://www.themoviedb.org/t/p/original/4WJ9kNejI8apl3f8hMNwo8V3hGT.jpg",
                            ReleaseDate = new DateTime(1980, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cosmos",
                            Type = (short)1
                        },
                        new
                        {
                            Id = 71,
                            Overview = "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
                            PosterPath = "https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_FMjpg_UX1000_.jpg",
                            ReleaseDate = new DateTime(2011, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Game of Thrones",
                            Type = (short)1
                        },
                        new
                        {
                            Id = 72,
                            Overview = "New Jersey mob boss Tony Soprano deals with personal and professional issues in his home and business life that affect his mental state, leading him to seek professional psychiatric counseling.",
                            PosterPath = "https://m.media-amazon.com/images/M/MV5BZGJjYzhjYTYtMDBjYy00OWU1LTg5OTYtNmYwOTZmZjE3ZDdhXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_FMjpg_UX1000_.jpg",
                            ReleaseDate = new DateTime(1999, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Sopranos",
                            Type = (short)1
                        });
                });

            modelBuilder.Entity("JAP_Task_1_MoviesApi.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            UserId = 1,
                            Value = 4.5999999999999996
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 2,
                            UserId = 1,
                            Value = 4.5
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 3,
                            UserId = 1,
                            Value = 4.5
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 4,
                            UserId = 1,
                            Value = 4.5
                        },
                        new
                        {
                            Id = 5,
                            MovieId = 5,
                            UserId = 1,
                            Value = 4.4000000000000004
                        },
                        new
                        {
                            Id = 6,
                            MovieId = 6,
                            UserId = 1,
                            Value = 4.3499999999999996
                        },
                        new
                        {
                            Id = 7,
                            MovieId = 7,
                            UserId = 1,
                            Value = 4.2999999999999998
                        },
                        new
                        {
                            Id = 8,
                            MovieId = 8,
                            UserId = 1,
                            Value = 4.2000000000000002
                        },
                        new
                        {
                            Id = 9,
                            MovieId = 9,
                            UserId = 1,
                            Value = 4.2000000000000002
                        },
                        new
                        {
                            Id = 10,
                            MovieId = 10,
                            UserId = 1,
                            Value = 4.2000000000000002
                        },
                        new
                        {
                            Id = 11,
                            MovieId = 60,
                            UserId = 1,
                            Value = 4.2000000000000002
                        },
                        new
                        {
                            Id = 12,
                            MovieId = 61,
                            UserId = 1,
                            Value = 4.2000000000000002
                        },
                        new
                        {
                            Id = 13,
                            MovieId = 62,
                            UserId = 1,
                            Value = 4.2000000000000002
                        },
                        new
                        {
                            Id = 14,
                            MovieId = 63,
                            UserId = 1,
                            Value = 4.2000000000000002
                        },
                        new
                        {
                            Id = 15,
                            MovieId = 64,
                            UserId = 1,
                            Value = 4.2000000000000002
                        },
                        new
                        {
                            Id = 16,
                            MovieId = 65,
                            UserId = 1,
                            Value = 4.2000000000000002
                        });
                });

            modelBuilder.Entity("JAP_Task_1_MoviesApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 9, 15, 21, 40, 17, 840, DateTimeKind.Local).AddTicks(6044),
                            FirstName = "Admin",
                            LastName = "Admin",
                            PasswordHash = new byte[] { 204, 105, 9, 92, 53, 220, 143, 225, 194, 216, 51, 117, 166, 143, 17, 222, 216, 187, 78, 220, 242, 123, 0, 30, 25, 63, 35, 157, 235, 178, 94, 158, 32, 137, 56, 240, 56, 196, 124, 174, 79, 94, 72, 162, 51, 157, 9, 226, 106, 44, 173, 44, 131, 110, 193, 117, 187, 137, 120, 122, 14, 175, 37, 121 },
                            PasswordSalt = new byte[] { 100, 149, 125, 130, 50, 189, 254, 221, 245, 132, 160, 208, 124, 65, 42, 20, 99, 205, 185, 172, 159, 44, 72, 233, 249, 77, 91, 114, 195, 171, 14, 9, 138, 218, 111, 96, 199, 45, 248, 197, 28, 142, 239, 156, 180, 108, 54, 42, 157, 177, 139, 31, 220, 206, 251, 250, 40, 164, 24, 28, 21, 187, 134, 139, 242, 112, 157, 7, 2, 133, 204, 96, 155, 158, 40, 195, 46, 164, 180, 163, 238, 89, 91, 56, 229, 178, 231, 190, 193, 44, 147, 105, 17, 76, 134, 234, 147, 161, 134, 98, 95, 155, 235, 61, 89, 113, 5, 37, 35, 53, 0, 205, 138, 79, 161, 232, 143, 215, 198, 73, 56, 168, 141, 186, 170, 2, 16, 39 },
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("ActorMovie", b =>
                {
                    b.HasOne("JAP_Task_1_MoviesApi.Models.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JAP_Task_1_MoviesApi.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JAP_Task_1_MoviesApi.Models.Rating", b =>
                {
                    b.HasOne("JAP_Task_1_MoviesApi.Models.Movie", null)
                        .WithMany("Ratings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JAP_Task_1_MoviesApi.Models.User", null)
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JAP_Task_1_MoviesApi.Models.Movie", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("JAP_Task_1_MoviesApi.Models.User", b =>
                {
                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
